### ISSUE TITLE
Preferred technology

### ISSUE THREAD

**Issue by JanKaifer** [JanKaifer/cell-lab-computer#1]
So we can go with pygame or web (and fancy js library).
What's your opinion?

**Comment by NicOfNoomers** [comment]
It depends on what platforms we will release. I think that the game might be a success if we make it less scientific than the one that you showed on play Store. So our main goal will be to deploy on multiple platforms. Today web games are not that popular but with the help of Cordova we can deploy web code into Android Os and Windows platforms so yeah I think that Angular Js or pure Javascript will make it happen! What do you think?

**Comment by JanKaifer** [comment]
I don't have much experience with JS it looks like best option. So now even bigger problem which JS library to use 😂😂.

And about the game. Maybe it looks little complicated for newcomers but I would definitely try to have something like advanced where it could be as scientific as original game maybe little bit more.

**Comment by NicOfNoomers** [comment]
I think that the advanced idea is very important and I think that we can make levels randomly! Of course we can implement new designs and new features. I think it will be great. For the Js libraries we choose what suites you best! I do not mind! We can start with basic JS and if it becomes very complicated we change to something more Object Oriented

**Comment by JanKaifer** [comment]
Agree, however I would try to code as much object oriented as possible, since than it will be much easier to change graphics library or other components.

**Comment by NicOfNoomers** [comment]
No prob we can use angulare Js or React Js I have worked with both! And they both are OOP enabled!

**Comment by NicOfNoomers** [comment]
No prob React we Use!

**Comment by JanKaifer** [comment]
Now there are thousands of React project templates from react-startapp (or what's name of that script) to some strange single folder layouts so if you have some experience could you please create project? And we need to choose package manager. I always used npm however there are lot of anlernatives if you have any experience with them?

**Comment by NicOfNoomers** [comment]
I am also used to npm so we agree on that. I will try to push a react template as fast as possible

**Comment by NicOfNoomers** [comment]
come to the trello board so we can have an easier mean of communication!

**Comment by JanKaifer** [comment]
no need for speed I don't have much spare time - I'm installing new system so I writing from my phone.

**Comment by JanKaifer** [comment]
I can start by tomorrow
