### ISSUE TITLE
Do you expect any profit from this?

### ISSUE THREAD

**Issue by JanKaifer** [JanKaifer/cell-lab-computer#2]
I forgot to ask you about licence and stuff like that. I'll be happy if we make it playable so I' voting for opensource but that's up to you.

**Comment by NicOfNoomers** [comment]
You never know if a project will make profit before building it! So we can make the repository private and add people who want to contribute but I do not know If we have to keep it open source or not! We can but we need to ensure that there is copies of our game and so on! We do not want others to copy our game and publish it as their own work! But I am not sure what we should do. As for the money I think that we can implement an Ad revenue system but we have a lot of time till then! 

If we want to transform this into private we can use GitLab they offer private repos for free!

**Comment by JanKaifer** [comment]
I'm student so I have privat repos on GitHub too. If I understand correctly we can just change licence to something that doesn't allow copying. Something more scrict that MIT. And later on we can leave version v1 open and add new features like cloud saves to v2 in some proprietary fork of this thing.

**Comment by NicOfNoomers** [comment]
We speak the same language!! I like this !

**Comment by NicOfNoomers** [comment]
I have to study the licences I have never used one different than the MIT so yeah use the one that you believe suits us the best and then if we find something better we change to it!

**Comment by JanKaifer** [comment]
and about rights and stuff I I'm afraid that name cell lab is copyrighted so we need to think about that too.
