### ISSUE TITLE
Are we going to use something like redux?

### ISSUE THREAD

**Issue by JanKaifer** [JanKaifer/cell-lab-computer#9]
@nmichaelsdu

**Comment by NicOfNoomers** [comment]
I am not very sure how redux works but let me read more about it and I will respond soon!

**Comment by NicOfNoomers** [comment]
I am not very sure how redux works but let me read more about it and I will respond soon!

**Comment by NicOfNoomers** [comment]
I am not very sure how redux works but let me read more about it and I will respond soon!

**Comment by NicOfNoomers** [comment]
I am not very sure how redux works but let me read more about it and I will respond soon!

**Comment by JanKaifer** [comment]
thx
